### ISSUE TITLE
TESTNET UPGRADE

### ISSUE THREAD

**Issue by noandrea** [elesto-dao/elesto#118]
- [x] Mint module ?
- [x] Credential module ?
- [x] ICA ?

**Comment by noandrea** [comment]
Scheduled for 21st of June

**Comment by noandrea** [comment]
here the instructions for the migration https://github.com/elesto-dao/elesto/pull/147#issue-1274912271

**Comment by noandrea** [comment]
proposal for the upgrade has been submitted, voting is underway:

```
elestod query gov proposals -o json | jq
{
  "proposals": [
    {
      "proposal_id": "1",
      "content": {
        "@type": "/cosmos.upgrade.v1beta1.SoftwareUpgradeProposal",
        "title": "testnet-upgrade-2022-06-21 upgrade",
        "description": "testnet upgrade introducing mint and credentials module",
        "plan": {
          "name": "testnet-upgrade-2022-06-21",
          "time": "0001-01-01T00:00:00Z",
          "height": "1151280",
          "info": "",
          "upgraded_client_state": null
        }
      },
      "status": "PROPOSAL_STATUS_VOTING_PERIOD",
      "final_tally_result": {
        "yes": "0",
        "abstain": "0",
        "no": "0",
        "no_with_veto": "0"
      },
      "submit_time": "2022-06-20T15:07:20.362575929Z",
      "deposit_end_time": "2022-06-22T15:07:20.362575929Z",
      "total_deposit": [
        {
          "denom": "utsp",
          "amount": "210000000"
        }
      ],
      "voting_start_time": "2022-06-20T15:07:20.362575929Z",
      "voting_end_time": "2022-06-22T15:07:20.362575929Z"
    }
  ],
  "pagination": {
    "next_key": null,
    "total": "0"
  }
}

```

**Comment by noandrea** [comment]
upgrade is scheduled for around 10:30 Friday the 24

**Comment by noandrea** [comment]
upgrade failed, here the logs of the node-0

```
Jun 24 11:53:20 elesto-node-0 cosmovisor[15960]: 11:53AM INF indexed block height=1151279 module=txindex
Jun 24 11:53:25 elesto-node-0 cosmovisor[15960]: 11:53AM INF Timed out dur=4961.395642 height=1151280 module=consensus round=0 step=1
Jun 24 11:53:25 elesto-node-0 cosmovisor[15960]: 11:53AM INF received proposal module=consensus proposal={"Type":32,"block_id":{"hash":"B985D54FDE2E87AE34127910AF29ADC824EF36BA134925BEFD03D3DDAEB33AE7","parts":{"hash":"35C48DAEE4A0A3971B291973853BF30B025C07CA32EAE9B6A55546D9EE33DEAF","total":1}},"height":1151280,"p>
Jun 24 11:53:25 elesto-node-0 cosmovisor[15960]: 11:53AM INF received complete proposal block hash=B985D54FDE2E87AE34127910AF29ADC824EF36BA134925BEFD03D3DDAEB33AE7 height=1151280 module=consensus
Jun 24 11:53:26 elesto-node-0 cosmovisor[15960]: 11:53AM INF finalizing commit of block hash=B985D54FDE2E87AE34127910AF29ADC824EF36BA134925BEFD03D3DDAEB33AE7 height=1151280 module=consensus num_txs=0 root=C668CEC804D1850303B644B143562B72025648A22DC5A7E6D88CD16428E03EA6
Jun 24 11:53:26 elesto-node-0 cosmovisor[15960]: 11:53AM ERR UPGRADE "testnet-upgrade-2022-06-21" NEEDED at height: 1151280:
Jun 24 11:53:26 elesto-node-0 cosmovisor[15960]: 11:53AM ERR CONSENSUS FAILURE!!! err="UPGRADE \"testnet-upgrade-2022-06-21\" NEEDED at height: 1151280: " module=consensus stack="goroutine 116 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).r>
Jun 24 11:53:26 elesto-node-0 cosmovisor[15960]: 11:53AM INF Stopping baseWAL service impl={"Logger":{}} module=consensus wal=/home/elesto/.elesto/data/cs.wal/wal
Jun 24 11:53:26 elesto-node-0 cosmovisor[15960]: 11:53AM INF Stopping Group service impl={"Dir":"/home/elesto/.elesto/data/cs.wal","Head":{"ID":"phUnJd4g6ged:/home/elesto/.elesto/data/cs.wal/wal","Path":"/home/elesto/.elesto/data/cs.wal/wal"},"ID":"group:phUnJd4g6ged:/home/elesto/.elesto/data/cs.wal/wal","Logger":{>
Jun 24 11:53:26 elesto-node-0 cosmovisor[15955]: 11:53AM INF Daemon shutting down in an attempt to restart module=cosmovisor
Jun 24 11:53:27 elesto-node-0 cosmovisor[15955]: 11:53AM INF pre-upgrade command does not exist. continuing the upgrade. module=cosmovisor
Jun 24 11:53:27 elesto-node-0 cosmovisor[15955]: 11:53AM INF upgrade detected, relaunching app=elestod module=cosmovisor
Jun 24 11:53:27 elesto-node-0 cosmovisor[15955]: 11:53AM INF running app args=["start"] module=cosmovisor path=/home/elesto/.elesto/cosmovisor/upgrades/testnet-upgrade-2022-06-21/bin/elestod
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF starting node with ABCI Tendermint in-process
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF Starting multiAppConn service impl=multiAppConn module=proxy
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF Starting localClient service connection=query impl=localClient module=abci-client
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF Starting EventBus service impl=EventBus module=events
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF Starting PubSub service impl=PubSub module=pubsub
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF Starting IndexerService service impl=IndexerService module=txindex
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF ABCI Handshake App Info hash="�h��\x04х\x03\x03�D�CV+r\x02VH�-ŧ�،�d(�>�" height=1151279 module=consensus protocol-version=0 software-version=2.0.0-rc1
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF ABCI Replay Blocks appHeight=1151279 module=consensus stateHeight=1151279 storeHeight=1151280
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF Replay last block using real app module=consensus
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF applying upgrade "testnet-upgrade-2022-06-21" at height: 1151280
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF adding a new module: credential
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF created new capability module=ibc name=ports/icahost
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF port binded module=x/ibc/port port=icahost
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF claimed capability capability=2 module=icahost name=ports/icahost
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF adding a new module: interchainaccounts
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF migrating module mint from version 1 to version 2
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF minted coins from module account amount=31709792stake from=mint module=x/bank
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: 11:53AM INF executed block height=1151280 module=consensus num_invalid_txs=0 num_valid_txs=0
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: panic: cannot delete latest saved version (1)
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: goroutine 1 [running]:
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).pruneStores(0xc0000f1ad0)
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/cosmos/cosmos-sdk@v0.45.4/store/rootmulti/store.go:447 +0x1b6
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Commit(0xc0000f1ad0)
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/cosmos/cosmos-sdk@v0.45.4/store/rootmulti/store.go:421 +0x175
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc0010bf380)
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:308 +0x1e9
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc000653d40)
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:264 +0xb6
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0xc000f308a0?)
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:93 +0x22
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: github.com/tendermint/tendermint/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc005d4b9f8, 0x8}}, {0xc005d4ba10, 0xf}, 0x1, 0x119130, {{0xc005dcb560, ...}, ...}, ...}, ...)
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/tendermint/tendermint@v0.34.19/state/execution.go:228 +0x269
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc005d4b9f8, 0x8}}, {0xc005d4ba10, 0xf}, 0x1, 0x119130, {{0xc005dcb560, ...}, ...}, ...}, ...)
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/tendermint/tendermint@v0.34.19/state/execution.go:180 +0x6ee
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc005d4b9f8, 0x8}}, {0xc005d4ba10, 0xf}, 0x1, 0x11912f, {{0xc005cbff40, ...}, ...}, ...}, ...)
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:503 +0x23c
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc005d4b9f8, 0x8}}, {0xc005d4ba10, 0xf}, 0x1, 0x11912f, {{0xc005cbff40, ...}, ...}, ...}, ...)
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:416 +0x7ae
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000f31f80, {0x257f5c0, 0xc000d8b380})
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc005d4b9f8, 0x8}}, {0xc005d4ba10, 0xf}, 0x1, 0x11912f, ...}, ...)
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: github.com/tendermint/tendermint/node.NewNode(0xc0001e0640, {0x256f840, 0xc000d65f40}, 0xc000e30ab0, {0x255aa40, 0xc004e64450}, 0x0?, 0x0?, 0xc000e30dc0, {0x2573830, ...}, ...)
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x577
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2586ee8, 0xc000d902d0}, {0x0, 0x0}, {0x2576ae8, 0xc00005b8d0}, ...}, ...)
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:272 +0x7db
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0001f6780?, {0x336a8f8?, 0x0?, 0x0?})
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:126 +0x169
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: github.com/spf13/cobra.(*Command).execute(0xc0001f6780, {0x336a8f8, 0x0, 0x0})
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: github.com/spf13/cobra.(*Command).ExecuteC(0xc000d28a00)
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: github.com/spf13/cobra.(*Command).Execute(...)
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/spf13/cobra@v1.4.0/command.go:902
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: github.com/spf13/cobra.(*Command).ExecuteContext(...)
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/spf13/cobra@v1.4.0/command.go:895
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x2336668?, {0xc000115a58, 0x14})
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/cosmos/cosmos-sdk@v0.45.4/server/cmd/execute.go:36 +0x1eb
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]: main.main()
Jun 24 11:53:43 elesto-node-0 cosmovisor[522077]:         github.com/elesto-dao/elesto/v2/cmd/elestod/main.go:22 +0x78
Jun 24 11:53:43 elesto-node-0 cosmovisor[15955]: 11:53AM ERR  error="exit status 2" module=cosmovisor
Jun 24 11:53:43 elesto-node-0 systemd[1]: cosmovisor.service: Main process exited, code=exited, status=1/FAILURE
Jun 24 11:53:43 elesto-node-0 systemd[1]: cosmovisor.service: Failed with result 'exit-code'.
Jun 24 11:53:46 elesto-node-0 systemd[1]: cosmovisor.service: Scheduled restart job, restart counter is at 1.
Jun 24 11:53:46 elesto-node-0 systemd[1]: Stopped Cosmovisor daemon.
Jun 24 11:53:46 elesto-node-0 systemd[1]: Started Cosmovisor daemon.

```
